#
#     Spit v1.0
#    Автор: Тимур
#   Телеграм: @tmrtrsvch
#
# /spit (spit.use) - Плюнуть
# /spit reload (spit.reload) - Перезагрузить конфигурацию
#

messages:
  no_permission: "&#23C100П&#21B400л&#1EA700е&#1C9A00в&#198D00к&#178000и&7&l: &fУ Вас нет прав для выполнения данной команды!"
  reload_usage: "&#23C100П&#21B400л&#1EA700е&#1C9A00в&#198D00к&#178000и&7&l: &fИспользуйте: &e/spit reload"
  config_reloaded: "&#23C100П&#21B400л&#1EA700е&#1C9A00в&#198D00к&#178000и&7&l: &fКонфигурация успешно перезагружена!"
  player_hit: "&#23C100П&#21B400л&#1EA700е&#1C9A00в&#198D00к&#178000и&7&l: &fВы попали плевком в игрока &e$p!"
  player_spat: "&#23C100П&#21B400л&#1EA700е&#1C9A00в&#198D00к&#178000и&7&l: &fИгрок &e$p попал в Вас плевком!"

settings:

  # Желательно не трогать, но можно потрогать, если нужно
  distance-threshold: 3.0
  direction-threshold: 0.8

  # Можно потрогать, но можно и не трогать
  velocity-multiplier: 1.0