#
#     Spit v1.0
#    Автор: Тимур
#   Телеграм: @tmrtrsvch
#
# /spit (spit.use) - Плюнуть
# /spit reload (spit.reload) - Перезагрузить конфигурацию
#

messages:
  no_permission: "&#1FAC00&lП&#1DA300&lл&#1C9A00&lе&#1A9200&lв&#198900&lк&#178000&lи&7&l: &fУ Вас нет прав для выполнения данной команды!"
  reload_usage: "&#1FAC00&lП&#1DA300&lл&#1C9A00&lе&#1A9200&lв&#198900&lк&#178000&lи&7&l: &fИспользуйте: &e/spit reload"
  config_reloaded: "&#1FAC00&lП&#1DA300&lл&#1C9A00&lе&#1A9200&lв&#198900&lк&#178000&lи&7&l: &fКонфигурация успешно перезагружена!"
  player_hit: "&#1FAC00&lП&#1DA300&lл&#1C9A00&lе&#1A9200&lв&#198900&lк&#178000&lи&7&l: &fВы попали плевком в игрока &e$p&f!"
  player_spat: "&#1FAC00&lП&#1DA300&lл&#1C9A00&lе&#1A9200&lв&#198900&lк&#178000&lи&7&l: &fИгрок &e$p &fпопал в Вас плевком!"

settings:

  # Желательно не трогать, но можно потрогать, если нужно
  distance-threshold: 3.0
  direction-threshold: 0.8

  # Можно потрогать, но можно и не трогать
  velocity-multiplier: 1.0